config/routes.rb
Rails.application.routes.draw do

    resources :user_messages, only: [:create]

    root 'categories#index'

    devise_for :admins

    resources :categories do
        resources :category_items do
            put :sort, on: :collection
        end
        put :sort, on: :collection
    end

    get 'download' => 'application#handle_file_output_request'

end

app/models/category_item.rb
# == Schema Information
#
# Table name: category_items
#
#  id                     :integer          not null, primary key
#  romaji                 :string(255)
#  kana                   :string(255)
#  title                  :string(255)
#  category_id            :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  female_audio_clip      :string(255)
#  male_audio_clip        :string(255)
#  slow_female_audio_clip :string(255)
#  slow_male_audio_clip   :string(255)
#  token                  :string(255)
#

class CategoryItem < ActiveRecord::Base
  belongs_to :category
  has_secure_token

  mount_uploader :female_audio_clip, FemaleAudioClipUploader
  mount_uploader :male_audio_clip, MaleAudioClipUploader
  mount_uploader :slow_female_audio_clip, SlowFemaleAudioClipUploader
  mount_uploader :slow_male_audio_clip, SlowMaleAudioClipUploader

  validates :romaji, presence: true, length: { maximum: 75 }
  validates :kana, presence: true, length: { maximum: 75 }
  validates :title, presence: true, length: { maximum: 75 }

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |category_item|
        csv << category_item.attributes.values_at(*column_names)
      end
    end
  end

  def self.get_play_icon_id_by_audio_clip(audio_clip={})
    get_id_by_type_for_audio_clip('play_icon', audio_clip)
  end

  def self.get_audio_clip_id_by_audio_clip(audio_clip={})
    get_id_by_type_for_audio_clip('audio_clip', audio_clip)
  end

  private

  def self.get_id_by_type_for_audio_clip(type='', audio_clip={})
    id = ''
    id += 'slow_' if audio_clip[:is_slow]
    id += audio_clip[:gender] + '_' + type
    id
  end

end

app/controllers/category_items_controller.rb
class CategoryItemsController < ApplicationController

    before_action :set_category
    before_action :set_category_item, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_admin!

    def index
        @category_items = CategoryItem.where(category_id: params[:id]).order(position: :asc)
    end

    def show
    end

    def new
        @category_item = @category.category_items.new
    end

    def edit
    end

    def create
        @category_item = @category.category_items.new(category_item_params)
        @category_item.position = next_available_pos
        if @category_item.save
            flash[:success] = 'Category item was successfully created.'
            redirect_to @category
        else
            render :new
        end
    end

    def update
        if @category_item.update(category_item_params)
            flash[:success] = 'Category item was successfully updated.'
            redirect_to @category
        else
            render :edit
        end
    end

    def destroy
        @category_item.destroy
        flash[:success] = 'Category item was successfully destroyed.'
        redirect_to @category
    end

    def sort
        params[:order].each do |key, value|
            puts "********** #{value}"
            CategoryItem.find(value[:id]).update_attribute(:position, value[:position])
        end
        render :nothing => true
    end

    private

    def set_category
        @category = Category.find(params[:category_id])
    end

    def set_category_item
        @category_item = CategoryItem.where(category: @category, id: params[:id]).take
    end

    def category_item_params
        params.require(:category_item).permit(:romaji,
                                              :kana,
                                              :title,
                                              :category_id,
                                              :female_audio_clip,
                                              :slow_female_audio_clip,
                                              :male_audio_clip,
                                              :slow_male_audio_clip,
                                              :position)
    end

    def next_available_pos
        pos_arr = Array.new
        CategoryItem.all.each do |c|
            pos_arr << c.position
        end
        return pos_arr.blank? ? 0 : pos_arr.max + 1
    end

end

app/views/category_items/_audio_playback.html.erb
<% if audio_clip[:audio_data].blank? %>
    (No registered audio clip is available)
<% else %>
    <% play_icon_id = CategoryItem.get_play_icon_id_by_audio_clip(audio_clip) %>
    <% audio_clip_id = CategoryItem.get_audio_clip_id_by_audio_clip(audio_clip) %>

    <audio id=<%= audio_clip_id %> controls preload="auto">
        <source src="<%= audio_clip[:audio_data] %>" type="audio/aac">
        Your computer does not support audio playback.
    </audio>
<% end %>

app/views/category_items/_form.html.erb
<%= form_for [@category, @category_item] do |f| %>

    <%= display_errors_for_object @category_item %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, { class: 'form-control', tabindex: 1 } %>
    </div>

    <div class="form-group">
      <%= f.label :kana %><br>
      <%= f.text_field :kana, { class: 'form-control', tabindex: 2 } %>
    </div>

    <div class="form-group">
      <%= f.label :romaji %><br>
      <%= f.text_field :romaji, { class: 'form-control', tabindex: 3 } %>
    </div>

    <div class="form-group">
      <%= f.label 'Current female audio clip' %>
      <%= render partial: 'audio_playback',
                 locals: { audio_clip: { audio_data: @category_item.female_audio_clip,
                                         gender: "female",
                                         is_slow: false } } %>
    </div>

    <div class="form-group">
      <%= f.label :female_audio_clip %><br>
      <%= f.file_field :female_audio_clip, { tabindex: 4 } %>
    </div>

    <div class="form-group">
      <%= f.label 'Current slow female audio clip' %>
      <%= render partial: 'audio_playback',
                 locals: { audio_clip: { audio_data: @category_item.slow_female_audio_clip,
                                         gender: "female",
                                         is_slow: true } } %>
    </div>

    <div class="form-group">
      <%= f.label :slow_female_audio_clip %><br>
      <%= f.file_field :slow_female_audio_clip, { tabindex: 5 } %>
    </div>

    <div class="form-group">
      <%= f.label 'Current male audio clip' %>
      <%= render partial: 'audio_playback',
                 locals: { audio_clip: { audio_data: @category_item.male_audio_clip,
                                         gender: "male",
                                         is_slow: false } } %>
    </div>

    <div class="form-group">
      <%= f.label :male_audio_clip %><br>
      <%= f.file_field :male_audio_clip, { tabindex: 6 } %>
    </div>

    <div class="form-group">
      <%= f.label 'Current slow male audio clip' %>
      <%= render partial: 'audio_playback',
                 locals: { audio_clip: { audio_data: @category_item.slow_male_audio_clip,
                                         gender: "male",
                                         is_slow: true } } %>
    </div>

    <div class="form-group">
      <%= f.label :slow_male_audio_clip %><br>
      <%= f.file_field :slow_male_audio_clip, { tabindex: 7 } %>
    </div>

    <div class="form-group">
      <%= f.submit nil, { class: 'btn btn-primary', tabindex: 8 } %>
    </div>

<% end %>

app/views/category_items/edit.html.erb
<h1>Editing Category Item</h1>

<%= render 'form' %>

<%= link_to 'Show', category_category_item_path(@category_item.category.id, @category_item.id) %> |
<%= link_to 'Back', categories_path %>

app/views/category_items/new.html.erb
<h1>New Category Item</h1>

<%= render 'form' %>
<%= link_to 'Back', category_path(params[:category_id]) %>

app/views/category_items/show.html.erb
<p class="category_item_row">
  <strong>Romaji:</strong>
  <%= @category_item.romaji %>
</p>

<p class="category_item_row">
  <strong>Kana:</strong>
  <%= @category_item.kana %>
</p>

<p class="category_item_row">
  <strong>Title:</strong>
  <%= @category_item.title %>
</p>

<p class="category_item_row">
  <strong>Parent category:</strong>
  <%= @category_item.category.title %>
</p>

<p class="category_item_row">
  <strong>Female Audio Clip</strong>
  <%= render partial: 'audio_playback',
             locals: { audio_clip: { audio_data: @category_item.female_audio_clip,
                                     gender: "female",
                                     is_slow: false } } %>
</p>

<p class="category_item_row">
  <strong>Slow Female Audio Clip</strong>
  <%= render partial: 'audio_playback',
             locals: { audio_clip: { audio_data: @category_item.slow_female_audio_clip,
                                     gender: "female",
                                     is_slow: true } } %>
</p>

<p class="category_item_row">
  <strong>Male Audio Clip</strong>
  <%= render partial: 'audio_playback',
             locals: { audio_clip: { audio_data: @category_item.male_audio_clip,
                                     gender: "male",
                                     is_slow: false } } %>
</p>

<p class="category_item_row">
  <strong>Slow Male Audio Clip</strong>
  <%= render partial: 'audio_playback',
             locals: { audio_clip: { audio_data: @category_item.slow_male_audio_clip,
                                     gender: "male",
                                     is_slow: true } } %>
</p>

<%= link_to 'Edit', edit_category_category_item_path(@category_item.category.id, @category_item.id) %> |
<%= link_to 'Back', category_path(@category_item.category) %>