config/routes.rb
Rails.application.routes.draw do

    resources :user_messages, only: [:create]

    root 'categories#index'

    devise_for :admins

    resources :categories do
        resources :category_items do
            put :sort, on: :collection
        end
        put :sort, on: :collection
    end

    get 'download' => 'application#handle_file_output_request'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :category_items, dependent: :restrict_with_error

  validates :title, presence: true, length: { maximum: 75 }

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |category|
        csv << category.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_admin!

    def index
        @categories = Category.all.order(position: :asc)
        @user_messages = UserMessage.all.order(created_at: :desc).page(params[:page]).per(5)
    end

    def show
        @category_items = CategoryItem.where(category_id: params[:id]).order(position: :asc)
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(category_params)
        @carousel_image.position = next_available_pos

        if @category.save
            flash[:success] = 'Category was successfully created.'
            redirect_to @category
        else
            render :new
        end
    end

    def update
        if @category.update(category_params)
            flash[:success] = 'Category was successfully updated.'
            redirect_to @category
        else
            render :edit
        end
    end

    def destroy
        if @category.destroy
            flash[:success] = 'Category was successfully destroyed.'
        end
        redirect_to categories_url
    end

    def sort
        params[:order].each do |key, value|
            Category.find(value[:id]).update_attribute(:position, value[:position])
        end
        render :nothing => true
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:title, :position)
    end

    def next_available_pos
        pos_arr = Array.new
        Category.all.each do |c|
            pos_arr << c.position
        end
        return pos_arr.blank? ? 0 : pos_arr.max + 1
    end

end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

    <%= display_errors_for_object @category %>

    <div class="form-group">
      <%= f.text_field :title, { class: 'form-control', placeholder: 'Title', tabindex: 1 } %>
    </div>

    <div class="form-group">
      <%= f.submit nil, { class: 'btn btn-primary', tabindex: 2 } %>
    </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h3>Categories
  <small><%= link_to '+ New Category', new_category_path %></small>
</h3>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>Title (no. items)</th>
    <th>Options</th>
    <th></th>
  </tr>
  </thead>
  <tbody class="sortable">
  <% @categories.each do |category| %>
          <tr class="draggable" data-id="<%= category.id %>">
            <td class="td-drag-icon"><span class="glyphicon glyphicon-move"></span></td>
            <td><%= link_to category.title + ' (' + category.category_items.count.to_s + ')', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
  <% end %>
  </tbody>
</table>

<hr>

<%= render :partial => 'common/user_messages' %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h3>Listing Category Items for '<%= @category.title %>'
  <small><%= link_to '+ New Category item', new_category_category_item_path(@category.id), {tabindex: 1} %></small>
</h3>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Kana</th>
    <th>Romaji</th>
    <th>Options</th>
    <th></th>
  </tr>
  </thead>

  <tbody class="sortable" data-category_id="<%= @category.id %>">
  <% @category_items.each do |category_item| %>
          <tr class="draggable" data-id="<%= category_item.id %>">
            <td class="td-drag-icon"><span class="glyphicon glyphicon-move"></span></td>
            <td><%= link_to category_item.title, category_category_item_path(@category.id, category_item) %></td>
            <td><%= category_item.kana %></td>
            <td><%= category_item.romaji %></td>
            <td><%= link_to 'Edit', edit_category_category_item_path(@category.id, category_item) %></td>
            <td><%= link_to 'Destroy', category_category_item_path(@category.id, category_item), method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>