config/routes.rb
Rails.application.routes.draw do

    resources :user_messages, only: [:create]

    root 'categories#index'

    devise_for :admins

    resources :categories do
        resources :category_items do
            put :sort, on: :collection
        end
        put :sort, on: :collection
    end

    get 'download' => 'application#handle_file_output_request'

end

app/views/common/_error_message.html.erb
<% if object && object.errors.present? %>

    <div class="alert alert-danger">

      <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>

      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>

    </div>

<% end %>

app/views/common/_flash.html.erb
<% flash.each do |key, val| %>
    <div class="container">
      <div class="alert alert-<%= infer_alert_class_by_flash_key(key) %>">
        <%= val %>
      </div>
    </div>
<% end unless flash.blank? %>

app/views/common/_navigation.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a href="/categories" class="navbar-brand">
          <%= image_tag 'taptaro.png' %>
        </a>
      </div>

      <% unless current_admin.nil? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Export', download_path, 'data-confirm' => 'Press OK to download latest taptaro files.', 'data-no-turbolink' => true %></li>
            <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
          </ul>
      <% end %>

    </div>

  </nav>

</header>

app/views/common/_user_messages.html.erb
<h3>Feedback</h3>
<h6><%= page_entries_info @user_messages, :entry_name => 'message' %></h6>

<% if @user_messages.any? %>
    <%= paginate @user_messages %>
    <ul class="list-group">
      <% @user_messages.each do |m| %>
          <li class="list-group-item">
            <h6 class="list-group-item-heading"><%= m.created_at.strftime("%B %d, %Y") %></h6>

            <p class="list-group-item-text">"<%= m.message %>"</p>
          </li>
      <% end %>
    </ul>
<% end %>